### ISSUE TITLE
Prob

### ISSUE THREAD

**Issue by WinstonLiyt** [chenluda/zhihu-download#3]
好像没法用了，显示The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by WinstonLiyt** [comment]
需要修改一下send_file
改成这个return send_file(zip_data, as_attachment=True, download_name=markdown_title + ".zip")

**Comment by programme113** [comment]
可是我下载的居然没有文本，都是图片呢？

**Comment by WinstonLiyt** [comment]
文本应该是有的，但是有的链接下载会存在存放地址错误的问题，无法下载

**Comment by chenluda** [comment]
感谢两位提出的 bug @programme113 @WinstonLiyt 。2023-08-16 08:51:31 测试，没有出现相关错误。

> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. @WinstonLiyt 

可能是开了 vpn，知乎那边拒绝了访问。

> 需要修改一下 send_file 改成这个 return send_file(zip_data, as_attachment=True, download_name=markdown_title + ".zip") @WinstonLiyt 

![image](https://github.com/chenluda/zhihu-download/assets/45784833/06b90f80-297b-4ec9-b172-45395aa97c1d)
flask 版本问题。 flask -2.2.0 前参数用的是 attachment_filename。

> 可是我下载的居然没有文本，都是图片呢？ @programme113 

md 文件与图像文件夹在同级。如果方便的话可以提供下出现问题的网址吗？
