### ISSUE TITLE
文章中的链接是否可以加入导出

### ISSUE THREAD

**Issue by gaozhao7** [chenluda/zhihu-download#4]
大佬，导出的内容里面没有包含链接内容，这块能否优化？
![image](https://github.com/chenluda/zhihu-download/assets/36031132/b5eabbe4-0222-44cc-9874-0ffef5484554)

**Comment by chenluda** [comment]
2023-08-19 10:30:00 Update main.py：修改代码，修复数学公式出现三 $ 的 bug；获取卡片链接。 @gaozhao7

**Comment by gaozhao7** [comment]
某些卡片链接获取不到标题的场景，是否可以通过url请求获取一下title呢

**Comment by chenluda** [comment]
感谢提醒，没仔细看，其实直接用 data-text 就可以获取到了，已修改代码。 @gaozhao7
