### ISSUE TITLE
几点问题和建议

### ISSUE THREAD

**Issue by Aswatthafei** [chenluda/zhihu-download#6]
**问题：**

- 今天（20231017）的代码版本有误 疑似main.py的第46行 重复粘贴
- 有些[文章](https://zhuanlan.zhihu.com/p/97649595)图片为png?，无法下载，可以加个if判断

**建议：**

- 可不可以考虑在文件前面加时间，有些专栏有几百篇，只按标题顺序很乱
- 源代码中对文件名称（不能以数字开头）和长度进行了限制，我这边测试下来没有什么问题，不知道作者是出于什么考虑限制的
- 考不考虑增加休眠时间，避免被反扒干掉。并记录当前传输到哪，即断点续传
- 考不考虑对跳转链接进行优化，现在的跳转连接都是“https://link.zhihu.com/?target=”，完全可以去掉

**Comment by chenluda** [comment]
感谢关注，后续我们会针对您提出的建议持续改进。 @Aswatthafei 

---
Glenn
2023-10-18 16:54:19

**Comment by chenluda** [comment]
再次感谢 @Aswatthafei 的建议，我们于 2023-10-27 15:29:23 修复改进了您提到的 bug 和建议：

- [x] main.py 的 46 行重复粘贴；
- [x] 有些文章图片为 png 格式，无法下载；
- [x] 在文件名称前加该文章的编辑时间；
- [x] 增加专栏文章下载的断点续传；
- [x] 对卡片链接进行优化，删除知乎安全链接前缀。
