### ISSUE TITLE
关于latex公式渲染的问题

### ISSUE THREAD

**Issue by czruby** [chenluda/zhihu-download#9]
在使用过程中发现当公式中使用了\tag{}标签时，公式使用单$包围无法被正常识别渲染，需要使用双$$
例如这篇知乎文章https://zhuanlan.zhihu.com/p/411502030

**Comment by chenluda** [comment]
感谢 @czruby 的提醒，
这个问题已解决，可以看下 [korruz 的解决方案](https://github.com/chenluda/zhihu-download/pull/8#issuecomment-1855599615)。

2023-12-27 10:57:22
